Create user model
wolox-training/jah-java pull request #6
Opened 2020-08-21 16:59 UTC by jdhiguita

## Summary
- Create User model
- Create custom exception to validate repeated books
## Trello Card
https://trello.com/c/5om9Sv1Y

2020-08-21 18:54 UTC, cramallo commented on src/main/java/wolox/training/exceptions/BookAlreadyOwnedException.java
> +public class BookAlreadyOwnedException extends RuntimeException {
this should not be in this pr

2020-08-21 20:07 UTC, jdhiguita commented on src/main/java/wolox/training/exceptions/BookAlreadyOwnedException.java
> +public class BookAlreadyOwnedException extends RuntimeException {
Check the trello card, in the instructions is to implement that validation

2020-08-21 20:25 UTC, Gianni-Nicolas requested changes
Good job, add some comments 😄

2020-08-21 20:25 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/models/User.java
> +    @ManyToMany
In the @ManyToMany tag we must indicate the type of cascade we want to use. Since by not indicating one, it will not do any function in this regard and it will bring you problems when interacting with the db.

It is usually recommended to use Casacade.ALL. But this is not always correct.
By saying ALL, you are saying: Persist, Merge, Refresh, Delete and Detach.

**Detach** is only so that something gets detached along the cascade when you detach an object from the persistence context manually. This almost never happens, so we won't focus on this point.

**Persist** says: If you persist the Users instance to the DB, then persist every item that this collection has in the DB as well.

**Delete** says: If you delete the Users instance from the DB, then delete every book item that this collection has in the DB as well.

**Merge** says: If you changed the in-memory values of the collection, then merge this changes to the DB so these are reflected there.

**Refresh** says: If something changed in the database values of the collection, then refresh those changes in the in-memory values.

Here is a [link](https://www.baeldung.com/jpa-cascade-types) explaining it.

In this case, we just need MERGE and REFRESH. [`@ManyToMany(cascade = {CascadeType.REFRESH, CascadeType.MERGE})`]
You can look at MERGE as the instruction to "merge" changes on the model back to the database.
But we're lacking the one that brings modifications iof the database to the model. And that's REFRESH :)

2020-08-21 20:25 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/models/User.java
> +    @JoinTable(name = "book_user",
The many to many relationship should work without the @JoinTable annotation since by default it defines the same thing that you have put. ([@JoinTable](https://stackoverflow.com/questions/5478328/in-which-case-do-you-use-the-jpa-jointable-annotation))

2020-08-21 20:25 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/models/User.java
> +    private List<Book> books;
When adding a many to many relation we need the other part of the relation. Now we should add the field into the book model. 

```
  @ManyToMany (mappedBy = "books")
  private List <User> user;
```
Remember to add its respective get as you did in this collection. 😄

2020-08-21 21:09 UTC, jdhiguita commented on src/main/java/wolox/training/models/User.java
> +    @ManyToMany
It's added type of cascade, thanks for explanation of each one.

2020-08-21 21:09 UTC, jdhiguita commented on src/main/java/wolox/training/models/User.java
> +    @JoinTable(name = "book_user",
Thanks for the information, great help

2020-08-21 21:09 UTC, jdhiguita commented on src/main/java/wolox/training/models/User.java
> +    private List<Book> books;
I'm sorry, between branches I forget this part

2020-08-21 22:26 UTC, cramallo approved these changes

2020-08-24 13:13 UTC, Gianni-Nicolas approved these changes

2020-08-25 14:45 UTC, merged